# Generated by Django 5.1.1 on 2024-10-03 20:30

import django.db.models.deletion
import parley.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The globally unique identifier of the object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp that the object was created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp that the object was last modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="The descriptive name of the evaluation prompts collection",
                        max_length=255,
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        default=None,
                        help_text="A description of the expected task or agent being evaluated",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Any notes or other descriptive information about the evaluation",
                        null=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="This prompt set should be used in evaluations of new models",
                    ),
                ),
            ],
            options={
                "verbose_name": "evaluation",
                "verbose_name_plural": "evaluations",
                "db_table": "evaluations",
                "ordering": ("-created",),
                "get_latest_by": "created",
            },
        ),
        migrations.CreateModel(
            name="LLM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The globally unique identifier of the object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp that the object was created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp that the object was last modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="The name of the model or model family being evaluated",
                        max_length=255,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="0.1.0",
                        help_text="The semantic version of the model for instance identification",
                        max_length=32,
                        validators=[parley.validators.validate_semver],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Any notes or other descriptive information about the model or training process",
                        null=True,
                    ),
                ),
                (
                    "model_config",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Configuration for instantiating the model",
                        null=True,
                    ),
                ),
                (
                    "generation_config",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="The standardized generation config of the model",
                        null=True,
                    ),
                ),
                (
                    "quantization_info",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Information about the quantization of the model, if any",
                        null=True,
                    ),
                ),
                (
                    "tokenizer_config",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="The standardized tokenization info of the model",
                        null=True,
                    ),
                ),
                (
                    "max_new_tokens",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="The maximum new tokens allowed during inferencing",
                        null=True,
                    ),
                ),
                (
                    "is_adapter_model",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Defines if this model is a base model or a LoRA",
                        null=True,
                    ),
                ),
                (
                    "trained_on",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="The timestamp that the model started training",
                        null=True,
                    ),
                ),
                (
                    "training_duration",
                    models.DurationField(
                        blank=True,
                        default=None,
                        help_text="The amount of time it took to train the model",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM",
                "verbose_name_plural": "LLMs",
                "db_table": "llms",
                "ordering": ("-trained_on",),
                "get_latest_by": "trained_on",
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The globally unique identifier of the object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp that the object was created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp that the object was last modified",
                    ),
                ),
                (
                    "system",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The system prompt specified to the LLM",
                        null=True,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        default=None,
                        help_text="The prompt used to generate an output from an LLM",
                    ),
                ),
                (
                    "history",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="An array of prompt IDs that precede this prompt during evaluation",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Any notes or other descriptive information about the prompt",
                        null=True,
                    ),
                ),
                (
                    "expected_output",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("json", "JSON"),
                            ("img", "Image"),
                            ("viz", "Visualization"),
                            ("csv", "CSV"),
                        ],
                        default="text",
                        help_text="Specify the expected type of output for the prompt to validate",
                        max_length=4,
                    ),
                ),
                (
                    "exclude",
                    models.BooleanField(
                        default=False,
                        help_text="Exclude this prompt from evaluations and from metrics",
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        help_text="The evaluation that this prompt is a part of",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="parley.evaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "prompt",
                "verbose_name_plural": "prompts",
                "db_table": "prompts",
                "ordering": ("-created",),
                "get_latest_by": "created",
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The globally unique identifier of the object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp that the object was created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp that the object was last modified",
                    ),
                ),
                (
                    "output",
                    models.TextField(
                        default=None,
                        help_text="The output generated by the LLM in response to the prompt",
                    ),
                ),
                (
                    "valid_output",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Based on the expected output, is it parseable; e.g. if the output is supposed to be JSON, is it correct?",
                        null=True,
                    ),
                ),
                (
                    "leaks_sensitive",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Does the output contain sensitive data that should not be leaked?",
                        null=True,
                        verbose_name="leaks sensitive data",
                    ),
                ),
                (
                    "is_confabulation",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Is the output a hallucination or confabulation?",
                        null=True,
                    ),
                ),
                (
                    "is_readable",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Does the output contain gramatically correct, understandable language?",
                        null=True,
                    ),
                ),
                (
                    "max_new_tokens",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Set this field if different from the model configuration",
                        null=True,
                    ),
                ),
                (
                    "inference_on",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="The timestamp that the LLM started the inferencing",
                        null=True,
                    ),
                ),
                (
                    "inference_duration",
                    models.DurationField(
                        blank=True,
                        default=None,
                        help_text="The amount of time it took to perform the inference",
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="The LLM that generated the specified response",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="responses",
                        to="parley.llm",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        help_text="The prompt that this is an LLM response to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="parley.prompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "response",
                "verbose_name_plural": "responses",
                "db_table": "responses",
                "ordering": ("-created",),
                "get_latest_by": "created",
            },
        ),
    ]
