# Generated by Django 5.1.1 on 2024-10-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parley", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="title",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="A title to specify for identifying the prompt",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sensitive",
            name="is_name",
            field=models.BooleanField(
                default=False,
                help_text="If the term is a proper name that may be extracted and fuzzy searched with NER",
            ),
        ),
    ]
