# Generated by Django 5.1.1 on 2024-10-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parley", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsereview",
            name="notes",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Any notes the reviewer would like to add about the output",
                null=True,
            ),
        ),
    ]
