# Generated by Django 5.1.1 on 2025-05-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parley", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modelevaluation",
            old_name="n_confabulations",
            new_name="n_factual",
        ),
        migrations.RenameField(
            model_name="modelevaluation",
            old_name="n_not_confabulation",
            new_name="n_not_factual",
        ),
        migrations.RemoveField(
            model_name="response",
            name="is_confabulation",
        ),
        migrations.RemoveField(
            model_name="responsereview",
            name="is_confabulation",
        ),
        migrations.AddField(
            model_name="modelevaluation",
            name="mean_helpfulness",
            field=models.FloatField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="modelevaluation",
            name="median_helpfulness",
            field=models.FloatField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="modelevaluation",
            name="n_correct_style",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="modelevaluation",
            name="n_incorrect_style",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="helpfulness",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Strongly Disagree"),
                    (2, "Disagree"),
                    (3, "Neutral"),
                    (4, "Agree"),
                    (5, "Strongly Agree"),
                ],
                default=None,
                help_text="This output is helpful to the reader",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="is_correct_style",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Is the output written in the correct style or tone?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="is_factual",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Is the output factually correct?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="responsereview",
            name="helpfulness",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Strongly Disagree"),
                    (2, "Disagree"),
                    (3, "Neutral"),
                    (4, "Agree"),
                    (5, "Strongly Agree"),
                ],
                default=None,
                help_text="This output is helpful to the reader",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="responsereview",
            name="is_correct_style",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Is the output written in the correct style or tone?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="responsereview",
            name="is_factual",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Is the output factually correct?",
                null=True,
            ),
        ),
    ]
