# Generated by Django 5.1.1 on 2024-10-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parley", "0002_prompt_title_sensitive_is_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelevaluation",
            name="confabulations_processed",
        ),
        migrations.RemoveField(
            model_name="modelevaluation",
            name="labels_processed",
        ),
        migrations.RemoveField(
            model_name="modelevaluation",
            name="output_type_processed",
        ),
        migrations.RemoveField(
            model_name="modelevaluation",
            name="readable_processed",
        ),
        migrations.RemoveField(
            model_name="modelevaluation",
            name="sensitive_processed",
        ),
        migrations.RemoveField(
            model_name="modelevaluation",
            name="similarity_processed",
        ),
        migrations.AddField(
            model_name="modelevaluation",
            name="n_invalid_output_type",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="modelevaluation",
            name="n_labeled_incorrectly",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="modelevaluation",
            name="n_no_sensitive_leaks",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="modelevaluation",
            name="n_not_confabulation",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="modelevaluation",
            name="n_not_readable",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="modelevaluation",
            name="n_not_similar",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="modelevaluation",
            name="n_confabulations",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="modelevaluation",
            name="n_labeled_correctly",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="modelevaluation",
            name="n_leaks_sensitive",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="modelevaluation",
            name="n_readable",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="modelevaluation",
            name="n_similar",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="modelevaluation",
            name="n_valid_output_type",
            field=models.IntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
    ]
